require("dotenv").config({ path: "./.env.local" });

module.exports = {
  overwrite: true,
  schema: "https://api.github.com/graphql",
  headers: {
    Authorization: `bearer ${process.env.GITHUB_PAT}`,
  },
  documents: "src/graphql/**/*.graphql",
  generates: {
    "__generated__/graphql.ts": {
      plugins: [
        {
          time: {
            message: "File generated at: ",
          },
        },
        {
          add: {
            content:
              "/* eslint-disable */\n/*\n * File automatically generated by graphql codegen\n * To regenerate this file, run\n *   `yarn regen-schema`\n * eslint and prettier are disabled for this file\n */\n",
          },
        },
        "typescript",
        "typescript-operations",
        "typescript-graphql-request",
      ],
    },
  },
};
